title: hibara428's Portfolio
author:
  name: hibara428
  email: hibara428@gmail.com
description: |
  ITエンジニア。インフラ/バックエンド/DevOps/システムアーキテクト。何か書く仕事とかしてみたい。
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed
show_excerpts: true
minima:
  skin: auto
  social_links:
    - platform: github
      user_url: 'https://github.com/hibara428'
    - platform: x
      user_url: 'https://x.com/hibara428'
    - platform: note
      user_url: 'https://note.com/hibara428'
    - platform: zenn
      user_url: 'https://zenn.dev/hibara428'
google_analytics: G-4DQ4RV5MJG
