title: hibara428's Portfolio
author:
  name: hibara428
  email: hibara428@gmail.com
description: |
  Web エンジニア。インフラ / バックエンド / DevOps エンジニア。システムアーキテクト。最近は書くお仕事をしてみたい。
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed
show_excerpts: true
minima:
  skin: auto
  social_links:
    - platform: github
      user_url: 'https://github.com/hibara428'
    - platform: x
      user_url: 'https://x.com/hibara428'
    - platform: note
      user_url: 'https://note.com/hibara428'
      title: note
    - platform: zenn
      user_url: 'https://zenn.dev/hibara428'
      title: zenn
google_analytics: G-4DQ4RV5MJG
